# Generated by Django 4.2.1 on 2023-05-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_demo', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
