# Generated by Django 4.2.1 on 2023-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_demo', '0005_employee_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_level',
            field=models.CharField(choices=[('jr.', 'Junior'), ('reg.', 'Regular'), ('sr.', 'Senior')], max_length=20),
        ),
    ]
