# Generated by Django 4.2.1 on 2023-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_demo', '0007_alter_employee_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_level',
            field=models.CharField(choices=[('jr.', 'Junior'), ('reg.', 'Regular'), ('sr.', 'Senior')], max_length=20, verbose_name='Seniority Level'),
        ),
    ]
