# Generated by Django 4.2.1 on 2023-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_demo', '0011_project_employee_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отдели'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-department', 'first_name', 'last_name'], 'verbose_name': 'Служител', 'verbose_name_plural': 'Служители'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекти'},
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
