# Generated by Django 4.2.1 on 2023-05-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_demo', '0012_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
