# Generated by Django 4.2.1 on 2023-05-19 12:41

from django.db import migrations, models
import temp_project.models_demo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('models_demo', '0013_alter_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(validators=[temp_project.models_demo.validators.validate_birthdate]),
        ),
    ]
