# Generated by Django 4.2.1 on 2023-06-02 07:53

import car_collection_app.car_collection.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


