# Generated by Django 4.2.1 on 2023-06-02 08:03

import car_collection_app.car_collection.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_collection', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('SPORT', 'Sports Car'), ('PICKUP', 'Pickup'), ('CROSSOVER', 'Crossover'), ('MINIBUS', 'Minibus'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('model', models.CharField(max_length=20, validators=[car_collection_app.car_collection.validators.min_length_validator])),
                ('year', models.IntegerField(validators=[car_collection_app.car_collection.validators.year_validator])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
