# Generated by Django 4.2.1 on 2023-06-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_collection', '0003_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
    ]
