# Generated by Django 4.2.1 on 2023-05-30 10:59

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/', validators=[petstagram.photos.validators.validate_file_size]),
        ),
    ]
