# Generated by Django 4.2.1 on 2023-06-01 09:58

import django.core.validators
from django.db import migrations, models
import my_plant_app.my_plant.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


