# Generated by Django 4.2.1 on 2023-06-01 10:08

import django.core.validators
from django.db import migrations, models
import my_plant_app.my_plant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('OUTDOOR', 'Outdoor Plants'), ('INDOOR', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), my_plant_app.my_plant.validators.validate_only_letters])),
                ('image_url', models.URLField()),
                ('description', models.CharField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
