# Generated by Django 4.2.1 on 2023-05-29 09:57

from django.db import migrations, models
import temp_project.forms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_person_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25, validators=[temp_project.forms.validators.validate_text])),
                ('priority', models.IntegerField(validators=[temp_project.forms.validators.ValueInRangeValidator(1, 10)])),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
