# Generated by Django 4.2.1 on 2023-05-29 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='assignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='forms.person2'),
            preserve_default=False,
        ),
    ]
