# Generated by Django 4.2.1 on 2023-05-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_person2_todo_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='person2',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
