# Generated by Django 4.2.1 on 2023-05-31 13:20

from django.db import migrations, models
import my_music_app.my_music.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Pop Music', 'Pop Music'), ('Jazz Music', 'Jazz Music'), ('R&B Music', 'R&B Music'), ('Rock Music', 'Rock Music'), ('Country Music', 'Country Music'), ('Dance Music', 'Dance Music'), ('Hip Hop Music', 'Hip Hop Music'), ('Other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('price', models.FloatField(validators=[my_music_app.my_music.validators.price_validator])),
            ],
        ),
    ]
