# Generated by Django 4.2.1 on 2023-05-31 13:24

from django.db import migrations, models
import my_music_app.my_music.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_music', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[my_music_app.my_music.validators.username_min_length, my_music_app.my_music.validators.username_content])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
