# Generated by Django 4.2.1 on 2023-05-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
    ]
