# Generated by Django 4.2.1 on 2023-06-02 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


