# Generated by Django 4.1.3 on 2022-12-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_employee_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='boolean_field',
            new_name='full_time',
        ),
    ]
