# Generated by Django 4.1.3 on 2022-12-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_department_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
