# Generated by Django 4.1.3 on 2022-12-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_employee_options_department_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
