# Generated by Django 4.1.3 on 2022-12-02 16:06

from django.db import migrations, models
import models_demos.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(validators=[models_demos.web.validators.validate_before_today]),
        ),
    ]
